---
- name: Deploy Banking Application
  hosts: test:prod
  become: true
  gather_facts: yes
  
  pre_tasks:
    - name: Verify required variables are defined
      assert:
        that:
          - docker_image is defined
          - docker_tag is defined
          - app_name is defined
          - host_port is defined
          - app_port is defined
        fail_msg: "Required variables are not defined"
        
  roles:
    - app
    
  post_tasks:
    - name: Display deployment information
      debug:
        msg: |
          Application deployed successfully!
          Image: {{ docker_image }}:{{ docker_tag }}
          Container: {{ app_name }}
          Port mapping: {{ host_port }}:{{ app_port }}
          Health check: http://{{ ansible_host }}:{{ host_port }}/actuator/health
